services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
      - chroma
    networks:
      - frontend
      - backend

  app:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - chroma
    command: uvicorn personal_ai_assistant.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mypia"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:6
    expose:
      - "6379"
    networks:
      - backend

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    expose:
      - "8000"
    networks:
      - backend

  celery_worker:
    build: .
    command: celery -A personal_ai_assistant.celery_app worker --loglevel=info
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - app
      - db
      - redis
    networks:
      - backend

  celery_beat:
    build: .
    command: celery -A personal_ai_assistant.celery_app beat --loglevel=info
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - app
      - db
      - redis
    networks:
      - backend

networks:
  frontend:
  backend:
    internal: false

volumes:
  postgres_data:
  redis_data:
  chroma_data:
  static:
