[tool.poetry]
name = "mypia"
version = "0.1.0"
description = "A personal AI assistant using public LLMs and local vector database"
authors = ["Michael Dodwell <michael@dodwell.us>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
rich = "^10.0.0"
pydantic = "^1.10.7"
python-dotenv = "^1.0.0"
imapclient = "^2.3.1"
caldav = "^1.3.0"
trafilatura = "^1.4.1"
spacy = "^3.5.2"
sqlalchemy = "^1.4.0"
celery = "^5.2.7"
redis = "^4.5.5"
chromadb = "^0.3.23"
sentence-transformers = "^2.2.2"
pygithub = "^1.58.2"
llama-cpp-python = "^0.1.50"
numpy = "^1.21.0"
aioimaplib = "^1.0.0"
aiosmtplib = "^2.0.1"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
flake8 = "^6.0.0"
mypy = "^1.3.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
sphinx = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mypia = "personal_ai_assistant.cli:cli"
