[tool.poetry]
name = "personal-ai-assistant"
version = "0.1.0"
description = "A personal AI assistant with local LLM and vector database"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
rich = "^13.3.5"
pydantic = "^1.10.7"
python-dotenv = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
flake8 = "^6.0.0"
mypy = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ai-assistant = "personal_ai_assistant.cli:cli"
