"""Add Token model

Revision ID: 068c862abdf6
Revises: 419c52c1fc74
Create Date: 2024-09-16 23:44:21.219847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '068c862abdf6'
down_revision: Union[str, None] = '419c52c1fc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_submissions_email', table_name='contact_submissions')
    op.drop_index('ix_contact_submissions_id', table_name='contact_submissions')
    op.drop_index('ix_contact_submissions_name', table_name='contact_submissions')
    op.drop_table('contact_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_submissions_pkey')
    )
    op.create_index('ix_contact_submissions_name', 'contact_submissions', ['name'], unique=False)
    op.create_index('ix_contact_submissions_id', 'contact_submissions', ['id'], unique=False)
    op.create_index('ix_contact_submissions_email', 'contact_submissions', ['email'], unique=False)
    # ### end Alembic commands ###
