"""Updated tasks

Revision ID: 349e236a8143
Revises: ea3aacaa8082
Create Date: 2024-09-17 09:42:14.165177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349e236a8143'
down_revision: Union[str, None] = 'ea3aacaa8082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
