"""Add UserPreference model

Revision ID: 419c52c1fc74
Revises: 7d9c51cbd4bb
Create Date: 2024-09-16 22:57:06.394102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '419c52c1fc74'
down_revision: Union[str, None] = '7d9c51cbd4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_submissions_email', table_name='contact_submissions')
    op.drop_index('ix_contact_submissions_id', table_name='contact_submissions')
    op.drop_index('ix_contact_submissions_name', table_name='contact_submissions')
    op.drop_table('contact_submissions')
    op.add_column('user_preferences', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('language', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_unique_constraint(None, 'user_preferences', ['user_id'])
    op.drop_column('user_preferences', 'key')
    op.drop_column('user_preferences', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_preferences', type_='unique')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_column('user_preferences', 'language')
    op.drop_column('user_preferences', 'theme')
    op.create_table('contact_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_submissions_pkey')
    )
    op.create_index('ix_contact_submissions_name', 'contact_submissions', ['name'], unique=False)
    op.create_index('ix_contact_submissions_id', 'contact_submissions', ['id'], unique=False)
    op.create_index('ix_contact_submissions_email', 'contact_submissions', ['email'], unique=False)
    # ### end Alembic commands ###
