"""Add Task model

Revision ID: 7d9c51cbd4bb
Revises: 3e9492ce7680
Create Date: 2024-09-16 22:54:19.763492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d9c51cbd4bb'
down_revision: Union[str, None] = '3e9492ce7680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_submissions_email', table_name='contact_submissions')
    op.drop_index('ix_contact_submissions_id', table_name='contact_submissions')
    op.drop_index('ix_contact_submissions_name', table_name='contact_submissions')
    op.drop_table('contact_submissions')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_preferences_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='user_preferences_pkey')
                    )
    op.create_table('contact_submissions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='contact_submissions_pkey')
                    )
    op.create_index('ix_contact_submissions_name', 'contact_submissions', ['name'], unique=False)
    op.create_index('ix_contact_submissions_id', 'contact_submissions', ['id'], unique=False)
    op.create_index('ix_contact_submissions_email', 'contact_submissions', ['email'], unique=False)
    # ### end Alembic commands ###
