def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flyway_schema_history',
    # ... (keep the existing table creation code)
    )
    op.create_index('flyway_schema_history_s_idx', 'flyway_schema_history', ['success'], unique=False)
    op.create_table('users',
    # ... (keep the existing table creation code)
    )
    op.create_table('llm_interactions',
    # ... (keep the existing table creation code)
    )
    op.create_table('notes',
    # ... (keep the existing table creation code)
    )
    op.create_table('emails',
    # ... (keep the existing table creation code)
    )
    op.create_table('tasks',
    # ... (keep the existing table creation code)
    )
    op.create_table('backups',
    # ... (keep the existing table creation code)
    )
    op.create_table('updates',
    # ... (keep the existing table creation code)
    )
    op.create_table('calendar_events',
    # ... (keep the existing table creation code)
    )
    op.create_table('user_preferences',
    # ... (keep the existing table creation code)
    )
    op.create_table('email_logs',
    # ... (keep the existing table creation code)
    )
    op.create_table('contact_submissions',
    # ... (keep the existing table creation code)
    )
    # ### end Alembic commands ###
