version: '3.8'

services:
  ai-assistant:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - /path/to/your/llama/models:/app/models
    environment:
      - DEBUG=True
      - LLM_MODEL_PATH=/app/models/your_model.bin
    command: hello
    depends_on:
      - redis
      - chroma

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-assistant
      - chroma

volumes:
  chroma-data:
