name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mypia
        environment-file: config/environment.yml
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate mypia
        poetry install
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate mypia
        poetry run pytest
    - name: Run linters
      shell: bash -l {0}
      run: |
        conda activate mypia
        poetry run black --check .
        poetry run flake8 .
        poetry run mypy .
